#!/bin/bash
cd /opt/nextees/middleware/user_projects/domains/soaosb_domain
mkdir AGJMSServerFileStore_auto_1 AGJMSServerFileStore_auto_2 AGJMSServerFileStore_auto_3 AGJMSServerFileStore_auto_4
mkdir BPMJMSServerFileStore_auto_1 BPMJMSServerFileStore_auto_2 BPMJMSServerFileStore_auto_3 BPMJMSServerFileStore_auto_4
mkdir PS6SOAJMSServerFileStore_auto_1 PS6SOAJMSServerFileStore_auto_2 PS6SOAJMSServerFileStore_auto_3 PS6SOAJMSServerFileStore_auto_4
mkdir SOAJMSServerFileStore_auto_1 SOAJMSServerFileStore_auto_2 SOAJMSServerFileStore_auto_3 SOAJMSServerFileStore_auto_4
mkdir UMSJMSServerFileStore_auto_1 UMSJMSServerFileStore_auto_2 UMSJMSServerFileStore_auto_3 UMSJMSServerFileStore_auto_4